.\" This man page was written by Markus Koschany. It is available
.\" under the same license as marsshooter, the GNU General Public License 3 or
.\" (at your option) any later version.
.TH M.A.R.S. "6" "September 2013" "M.A.R.S. - a ridiculous shooter" "User Commands"
.SH NAME
M.A.R.S. \- a ridiculous shooter
.SH SYNOPSIS
.B marsshooter
[\fIOptions\fR]
.SH DESCRIPTION
M.A.R.S is a two-dimensional space shooter game with excellent 2D-graphics, a
stunning amount of particles and shader support. It offers single- and
multiplayer gameplay, many impressive weapons and specials and customizable
ships.

In the year 3547 civilizations across the galaxy have settled their own
planets, living in peace and harmony with its environment. But outside the
placid habitats, the GREAT WAR is raging. As a famous fighter on your way to
never ending honor and prosperity, you have to protect your planet from the
imminent doom of your jealous neighbours!
.SH OPTIONS
.SS "Basic Options:"
.TP
\fB\-cfg\fR <Path>
Sets the absolute path to the configuration directory of the game.
.TP
\fB\-data\fR <Path>
Sets the absolute path to the data directory of the game,
which contains the folders sound/, tex/ and so on.
.SS "Miscellaneous Options:"
.TP
\fB\-help\fR
Print program options.
.TP
\fB\-version\fR
Print program version.
